# Generated by Django 6.0 on 2025-12-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='body',
            new_name='feedback',
        ),
    ]
