# Generated by Django 6.0 on 2026-01-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_body_feedback_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
